CIRCUITS_2024 = [
    'Bahrain', 'Jeddah', 'Melbourne', 'Suzuka', 'Shanghai', 'Miami',
    'Imola', 'Monaco', 'Montreal', 'Barcelona', 'Spielberg', 'Silverstone',
    'Hungaroring', 'Spa', 'Zandvoort', 'Monza', 'Baku', 'Singapore',
    'Austin', 'Mexico City', 'Interlagos', 'Las Vegas', 'Lusail', 'Yas Marina'
]
CIRCUIT_IMAGE_MAP = {
    'Bahrain': 'Bahrain.png',
    'Sakhir': 'Bahrain.png',
    'Jeddah': 'SaudiArabia.png',
    'Melbourne': 'Australia.png',
    'Suzuka': 'Japan.png',
    'Shanghai': 'China.png',
    'Miami': 'Miami.png',
    'Imola': 'EmiliaRomagna.png',
    'Monaco': 'Monaco.png',
    'Montreal': 'Canada.png',
    'Barcelona': 'Spain.png',
    'Circuit de Barcelona-Catalunya': 'Spain.png', 
    'Spielberg': 'Austria.png',
    'Silverstone': 'Silverstone.png',
    'Hungaroring': 'Hungary.png',
    'Spa': 'Belgium.png',
    'Spa-Francorchamps': 'Belgium.png',  
    'Zandvoort': 'Netherlands.png',
    'Monza': 'Italy.png',
    'Baku': 'Baku.png',
    'Singapore': 'Singapore.png',
    'Austin': 'USA.png',
    'Mexico City': 'Mexico.png',
    'Interlagos': 'Brazil.png',
    'São Paulo': 'Brazil.png',  
    'Las Vegas': 'LasVegas.png',
    'Lusail': 'Qatar.png',
    'Yas Marina': 'AbuDhabi.png',
    'Yas Island': 'AbuDhabi.png',  
    'Portimão': 'Portugal.png',
    'Mugello': 'Tuscany.png',
    'Nürburgring': 'Eifel.png',
    'Hockenheim': 'Germany.png',
    'Le Castellet': 'France.png',
    'Istanbul': 'Turkey.png',
    'Sochi': 'Russia.png'
}

SESSION_TYPES = ['Race', 'Qualifying', 'Practice 1', 'Practice 2', 'Practice 3']

DRIVERS_2024 = {
    'VER': 'Verstappen',
    'PER': 'Perez',
    'HAM': 'Hamilton',
    'RUS': 'Russell',
    'LEC': 'Leclerc',
    'SAI': 'Sainz',
    'NOR': 'Norris',
    'PIA': 'Piastri',
    'ALO': 'Alonso',
    'STR': 'Stroll',
    'OCO': 'Ocon',
    'GAS': 'Gasly',
    'BOT': 'Bottas',
    'ZHO': 'Zhou',
    'TSU': 'Tsunoda',
    'RIC': 'Ricciardo',
    'ALB': 'Albon',
    'SAR': 'Sargeant',
    'MAG': 'Magnussen',
    'HUL': 'Hulkenberg'
}

TEAMS_2024 = {
    'VER': 'RedBull', 'PER': 'RedBull',
    'HAM': 'Mercedes', 'RUS': 'Mercedes',
    'LEC': 'Ferrari', 'SAI': 'Ferrari',
    'NOR': 'McLaren', 'PIA': 'McLaren',
    'ALO': 'AstonMartin', 'STR': 'AstonMartin',
    'OCO': 'Alpine', 'GAS': 'Alpine',
    'BOT': 'KickSauber', 'ZHO': 'KickSauber',
    'TSU': 'RB', 'RIC': 'RB',
    'ALB': 'Williams', 'SAR': 'Williams',
    'MAG': 'Haas', 'HUL': 'Haas'
}

LOCATION_TO_EVENT_NAME_MAP = {
    'Sakhir': 'Bahrain Grand Prix',
    'Jeddah': 'Saudi Arabian Grand Prix',
    'Melbourne': 'Australian Grand Prix',
    'Suzuka': 'Japanese Grand Prix',
    'Shanghai': 'Chinese Grand Prix',
    'Miami': 'Miami Grand Prix',
    'Imola': 'Emilia Romagna Grand Prix',
    'Monaco': 'Monaco Grand Prix',
    'Montreal': 'Canadian Grand Prix',
    'Circuit de Barcelona-Catalunya': 'Spanish Grand Prix',
    'Barcelona': 'Spanish Grand Prix',
    'Spielberg': 'Austrian Grand Prix',
    'Silverstone': 'British Grand Prix',
    'Hungaroring': 'Hungarian Grand Prix',
    'Spa-Francorchamps': 'Belgian Grand Prix',
    'Zandvoort': 'Dutch Grand Prix',
    'Monza': 'Italian Grand Prix',
    'Baku': 'Azerbaijan Grand Prix',
    'Singapore': 'Singapore Grand Prix',
    'Austin': 'United States Grand Prix',
    'Mexico City': 'Mexico City Grand Prix',
    'São Paulo': 'São Paulo Grand Prix',
    'Las Vegas': 'Las Vegas Grand Prix',
    'Lusail': 'Qatar Grand Prix',
    'Yas Island': 'Abu Dhabi Grand Prix',
    'Portimão': 'Portuguese Grand Prix',
    'Mugello': 'Tuscan Grand Prix',
    'Nürburgring': 'Eifel Grand Prix',
    'Hockenheim': 'German Grand Prix',
    'Le Castellet': 'French Grand Prix',
    'Istanbul': 'Turkish Grand Prix',
    'Sochi': 'Russian Grand Prix'
}